version: 1.0.{build}
environment:
  azure_appid:
    secure: VLEJFOImH9Fs0R24k8sE8i3IoE3tu6N9LO4ZfyvL0OGCiTTopLU0ZW2ankyOJxP/
  azure_tenantid:
    secure: lTeuHZpv7YXOczmCmRHQ1oR311maLA3mLBbPVNaAFaaHGdsymoBT18UCuMhTqfiw
  azure_pw:
    secure: HLacbql7DTErFeyrvbhRer/sgQC6EUARkXnoCu5IHes=
  vm_admin_pw:
    secure: Ry2UOyp9ENPf/FeUv5KJWw==
image: WMF 5
install:
- ps: .\buildscripts\install.ps1
build_script:
- ps: .\buildscripts\build.ps1
test_script:
- ps: . .\New-TestEnvironment.Tests.ps1